# Generated by Django 3.2.6 on 2024-10-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.cronograma')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.descuento')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now=True)),
                ('ruta', models.CharField(max_length=255)),
                ('pago', models.ManyToManyField(to='generarreportes.Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('medioPago', models.CharField(max_length=50)),
                ('tipo', models.IntegerField(choices=[(1, 'pago'), (2, 'cobro')], default=1)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.pago')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.institucion'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estudiantes', models.ManyToManyField(to='generarreportes.Estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.institucion')),
            ],
        ),
        migrations.AddField(
            model_name='cronograma',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.curso'),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('formato', models.CharField(max_length=255)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.pago')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableF',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generarreportes.usuario')),
                ('estudiantes', models.ManyToManyField(to='generarreportes.Estudiante')),
            ],
            bases=('generarreportes.usuario',),
        ),
        migrations.AddField(
            model_name='pago',
            name='responsableF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generarreportes.responsablef'),
        ),
    ]
